FROM node:18-alpine as build
WORKDIR /usr/src/app-backend
COPY package*.json ./
# COPY angular.json ./
RUN npm install
COPY . .
# Exponer el puerto en el que tu aplicación escucha
EXPOSE 5000
# Comando para iniciar la aplicación
CMD ["node", "server.js"]

#######################
#frontend
WORKDIR /usr/src/app-frontend
COPY package*.json ./
# COPY angular.json ./
RUN npm install
COPY . .
RUN npm run build 



### NGINX
FROM nginx:1.24-alpine
RUN mkdir /usr/share/nginx/html/mern
COPY --from=build /usr/src/app-frontend/dist /usr/share/nginx/html/mern
COPY --from=build /usr/src/app-frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


